# Generated by Django 2.2.5 on 2019-11-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spirit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whiskey_type', models.CharField(choices=[('AMW', 'American Whiskey'), ('AMR', 'American Rye'), ('BOU', 'Bourbon Whiskey'), ('CAN', 'Canadian Whisky/Rye'), ('RUM', 'Rum')], default='BOU', max_length=1)),
                ('distillery', models.CharField(max_length=255, verbose_name='Distillery Name')),
                ('release', models.CharField(max_length=255, verbose_name='Release Name')),
                ('age', models.FloatField(verbose_name='Age')),
                ('proof', models.FloatField(verbose_name='Proof')),
                ('abv', models.FloatField(verbose_name='ABV')),
                ('single_barrel', models.BooleanField(verbose_name='Single Barrel?')),
                ('barrel_proof', models.BooleanField(verbose_name='Barrel Proof?')),
                ('store_pick', models.BooleanField(verbose_name='Store Pick?')),
                ('open_status', models.BooleanField(verbose_name='Is Open?')),
                ('valuation', models.FloatField(verbose_name='Valuation ($)')),
                ('value_date', models.DateField(verbose_name='Last Valued')),
                ('notes', models.TextField(verbose_name='Notes')),
            ],
        ),
    ]
