# Generated by Django 2.2.5 on 2019-11-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskey_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spirit',
            name='brand',
            field=models.CharField(default='null', max_length=255, verbose_name='Brand Name'),
            preserve_default=False,
        ),
    ]
