# Generated by Django 2.2.5 on 2019-11-28 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskey_list', '0003_auto_20191127_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spirit',
            name='abv',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(38), django.core.validators.MaxValueValidator(72)], verbose_name='ABV'),
        ),
        migrations.AlterField(
            model_name='spirit',
            name='age',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(45)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='spirit',
            name='proof',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(79), django.core.validators.MaxValueValidator(140)], verbose_name='Proof'),
        ),
    ]
