# Generated by Django 2.2.5 on 2019-11-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskey_list', '0004_auto_20191127_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='spirit',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
            preserve_default=False,
        ),
    ]
